#!/bin/sh

set -o errexit

if [ -z "${SRCROOT}" ]; then
	echo "Error: this script must be run by Xcode"
	exit 1
fi

WAD_NAME=prboom-plus.wad
WAD_PATH=${CONFIGURATION_BUILD_DIR}/${WAD_NAME}

# Check if WAD is up-to-date

if [ -e "${WAD_PATH}" ]; then
	WAD_TIME=`stat -f %c "${WAD_PATH}"`
fi

if [ -z ${WAD_TIME} ]; then
	NEED_BUILD=YES
else
	FILES=`find /Volumes/ramdisk/prboom-osx/prboom/data \( -name '*' \)`

	for FILE in ${FILES[@]}; do
		FILE_TIME=`stat -f %c "${FILE}"`
	
		if [ ${FILE_TIME} -gt ${WAD_TIME} ]; then
			NEED_BUILD=YES
			break
		fi
	done
fi

if [ -z ${NEED_BUILD} ]; then
	exit
fi

# Build WAD

PALETTE=(
	palette.rgb
)

LUMPS=(
	lumps/switches.lmp
	lumps/animated.lmp
	lumps/crbrick.lmp
	lumps/crtan.lmp
	lumps/crgray.lmp
	lumps/crgreen.lmp
	lumps/crbrown.lmp
	lumps/crgold.lmp
	lumps/crred.lmp
	lumps/crblue.lmp
	lumps/crblue2.lmp
	lumps/crorange.lmp
	lumps/cryellow.lmp
)

COLORMAPS=(
	lumps/watermap.lmp
)

TABLES=(
	lumps/sinetabl.lmp
	lumps/tangtabl.lmp
	lumps/tantoang.lmp
	lumps/gammatbl.lmp
	lumps/chexdeh.lmp
	lumps/bfgbex.lmp
	lumps/nervebex.lmp
	lumps/glshadow.lmp
	lumps/glfp.lmp
	lumps/glvp.lmp
	lumps/-prbhud-.lmp
	lumps/m_ammo.lmp
	lumps/m_armour.lmp
	lumps/m_arrow.lmp
	lumps/m_health.lmp
	lumps/m_key.lmp
	lumps/m_normal.lmp
	lumps/m_shadow.lmp
	lumps/m_power.lmp
	lumps/m_weap.lmp
	lumps/m_mark.lmp
)

SOUNDS=(
	sounds/dsdgsit.wav
	sounds/dsdgatk.wav
	sounds/dsdgact.wav
	sounds/dsdgdth.wav
	sounds/dsdgpain.wav
	sounds/dssecret.wav
	sounds/dsgibdth.wav
)

GRAPHICS=(
	graphics/dig0.ppm
	graphics/dig1.ppm
	graphics/dig2.ppm
	graphics/dig3.ppm
	graphics/dig4.ppm
	graphics/dig5.ppm
	graphics/dig6.ppm
	graphics/dig7.ppm
	graphics/dig8.ppm
	graphics/dig9.ppm
	graphics/diga.ppm
	graphics/digb.ppm
	graphics/digc.ppm
	graphics/digd.ppm
	graphics/dige.ppm
	graphics/digf.ppm
	graphics/digg.ppm
	graphics/digh.ppm
	graphics/digi.ppm
	graphics/digj.ppm
	graphics/digk.ppm
	graphics/digl.ppm
	graphics/digm.ppm
	graphics/dign.ppm
	graphics/digo.ppm
	graphics/digp.ppm
	graphics/digq.ppm
	graphics/digr.ppm
	graphics/digs.ppm
	graphics/digt.ppm
	graphics/digu.ppm
	graphics/digv.ppm
	graphics/digw.ppm
	graphics/digx.ppm
	graphics/digy.ppm
	graphics/digz.ppm
	graphics/dig45.ppm
	graphics/dig47.ppm
	graphics/dig58.ppm
	graphics/dig91.ppm
	graphics/dig93.ppm
	graphics/stbr123.ppm
	graphics/stbr124.ppm
	graphics/stbr125.ppm
	graphics/stbr126.ppm
	graphics/stbr127.ppm
	graphics/boxul.ppm
	graphics/boxuc.ppm
	graphics/boxur.ppm
	graphics/boxcl.ppm
	graphics/boxcc.ppm
	graphics/boxcr.ppm
	graphics/boxll.ppm
	graphics/boxlc.ppm
	graphics/boxlr.ppm
	graphics/stkeys6.ppm
	graphics/stkeys7.ppm
	graphics/stkeys8.ppm
	graphics/stcfn096.ppm
	graphics/m_butt1.ppm
	graphics/m_butt2.ppm
	graphics/m_colors.ppm
	graphics/m_palno.ppm
	graphics/m_palsel.ppm
	graphics/m_vbox.ppm
	graphics/cross1.ppm
	graphics/cross2.ppm
	graphics/cross3.ppm
	graphics/m_generl.ppm
	graphics/m_setup.ppm
	graphics/m_auto.ppm
	graphics/m_keybnd.ppm
	graphics/m_chat.ppm
	graphics/m_compat.ppm
	graphics/m_enem.ppm
	graphics/m_mess.ppm
	graphics/m_stat.ppm
	graphics/m_weap.ppm
	graphics/m_horsen.ppm
	graphics/m_versen.ppm
	graphics/prboom.ppm
	graphics/m_accel.ppm
	graphics/m_loksen.ppm
)

FLATS=(
	flats/-n0_tex-.ppm
)

SPRITES=(
	0,0,sprites/tnt1a0.ppm
	32,59,sprites/dogsd5.ppm
	32,59,sprites/dogsh5.ppm
	32,59,sprites/dogsc5.ppm
	32,59,sprites/dogsg5.ppm
	32,59,sprites/dogsb1.ppm
	32,59,sprites/dogsa5.ppm
	32,59,sprites/dogse5.ppm
	32,59,sprites/dogsc1.ppm
	32,59,sprites/dogsd1.ppm
	32,59,sprites/dogsb5.ppm
	32,59,sprites/dogsf5.ppm
	32,59,sprites/dogsa1.ppm
	32,59,sprites/dogse1.ppm
	32,59,sprites/dogsf1.ppm
	32,59,sprites/dogsd2d8.ppm
	32,59,sprites/dogsh2.ppm
	32,59,sprites/dogsg1.ppm
	32,59,sprites/dogsh8.ppm
	32,59,sprites/dogse8.ppm
	32,59,sprites/dogsd4d6.ppm
	32,59,sprites/dogsh4.ppm
	32,59,sprites/dogsa2a8.ppm
	32,59,sprites/dogse2.ppm
	32,59,sprites/dogsf8.ppm
	32,59,sprites/dogsh1.ppm
	32,59,sprites/dogsa4a6.ppm
	32,59,sprites/dogse4.ppm
	32,59,sprites/dogsb4b6.ppm
	32,59,sprites/dogsf4.ppm
	32,59,sprites/dogsh6.ppm
	32,59,sprites/dogsb2b8.ppm
	32,59,sprites/dogsf2.ppm
	32,59,sprites/dogsc2c8.ppm
	32,59,sprites/dogsg2.ppm
	32,59,sprites/dogsg6.ppm
	32,59,sprites/dogsc4c6.ppm
	32,59,sprites/dogsg4.ppm
	32,59,sprites/dogsg8.ppm
	32,59,sprites/dogsf6.ppm
	32,59,sprites/dogsn0.ppm
	32,59,sprites/dogse6.ppm
	32,59,sprites/dogsd3d7.ppm
	32,59,sprites/dogsh3.ppm
	32,59,sprites/dogsh7.ppm
	32,59,sprites/dogsi0.ppm
	32,59,sprites/dogsa3a7.ppm
	32,59,sprites/dogse3.ppm
	32,59,sprites/dogsb3b7.ppm
	32,59,sprites/dogsf3.ppm
	32,59,sprites/dogsf7.ppm
	32,59,sprites/dogse7.ppm
	32,59,sprites/dogsc3c7.ppm
	32,59,sprites/dogsg3.ppm
	32,59,sprites/dogsg7.ppm
	32,59,sprites/dogsj0.ppm
	32,59,sprites/dogsk0.ppm
	32,59,sprites/dogsl0.ppm
	32,59,sprites/dogsm0.ppm
	8,12,sprites/pls1a0.ppm
	9,12,sprites/pls1b0.ppm
	8,12,sprites/pls1c0.ppm
	9,12,sprites/pls1d0.ppm
	25,37,sprites/pls1e0.ppm
	25,37,sprites/pls1f0.ppm
	26,42,sprites/pls1g0.ppm
	7,10,sprites/pls2a0.ppm
	6,8,sprites/pls2b0.ppm
	5,6,sprites/pls2c0.ppm
	7,10,sprites/pls2d0.ppm
	11,16,sprites/pls2e0.ppm
)

WAD_CMDLINE=(
	-I "${SRCROOT}/prboom/data"
	-palette ${PALETTE[*]}
	-lumps ${LUMPS[*]}
	-marker C_START -lumps ${COLORMAPS[*]} -marker C_END
	-marker B_START -lumps ${TABLES[*]} -marker B_END
	-sounds ${SOUNDS[*]}
	-graphics ${GRAPHICS[*]}
	-marker FF_START -flats ${FLATS[*]} -marker FF_END
	-marker SS_START -sprites ${SPRITES[*]} -marker SS_END
	-o "${WAD_PATH}"
)

"${CONFIGURATION_BUILD_DIR}/rdatawad" ${WAD_CMDLINE[*]}
